export const grant_type = "password";
export const client_id =
  "3MVG9qQjGkWUbcrEPx0UB_Dt_8OiIw_9bCAlmY9FkeVce56T_NRPWWzBnBVAMBo8sC70j9eVIc7rhCIvbJtlW";
export const client_secret = "8510413236952768843";
export const username = "chris-blwc@force.com.procopy";
export const SFpassword = "pin@2019";
export const response_type = "token";
export const redirect_uri = "http://boltconcierge-2f0f9.firebaseapp.com";
export const scope = "refresh_token full";
export const display = "touch";
export const B_Questions = [
  "Hi, I'm your personal concierge. Your wish is my command. What name may I call you by?",
  "To what address can I send you your welcome pack?",
  "What is your data of birth?",
  "Finally I need your mobile to verify you aren't a robot.",
  "I've just sent you a sms.",
  "Amazing! We are good to go.",
  "Sorry! Verification Code mismatch. Try again."
];
export const PlaceHolder = [
  "First Name Second Name",
  "Number, StreetName, City, Postcode",
  "DD/MM/YYYY"
];
export const InfoGuide_Text = [
  "Welcome to your profile test user name... Help us to capture your suitability for properties and packages via Bolt.",
  "It takes less than 6 minutes. We reward you with money off our packages.",
  "Would you classify yourself as creative or functional person?",
  "What do you prefer doing in your spare time?",
  "What is your favourite pet?",
  "By saving £400 a month, how will you spend this?",
  "What is your current employment status?",
  "Gross annual salary?",
  "Status of your current address?",
  "Email address to verify account.",
  "Declaration that the information you have supplied is your own, true and accurate."
];
export const address_status = ["Owned", "Rented", "Living with parents"];
export const country_names = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua &amp; Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia &amp; Herzegovina",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Cayman Islands",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D Ivoire",
  "Croatia",
  "Cruise Ship",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "French West Indies",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyz Republic",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Pierre &amp; Miquelon",
  "Samoa",
  "San Marino",
  "Satellite",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "St Kitts &amp; Nevis",
  "St Lucia",
  "St Vincent",
  "St. Lucia",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor L'Este",
  "Togo",
  "Tonga",
  "Trinidad &amp; Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks &amp; Caicos",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (US)",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];
export const time_out = 1000;
export const sender_height = 50;
export const loadingGIF_height = 30;
export const first_bubble_height = 180;
export const fontsize = {
  salary: 18,
  email: 15
};
export const packages = [
  {
    img_name: "member.png",
    caption: "Members Pack",
    subcaption_1: "Insider members access to savings,",
    subcaption_2: "VIP treatment,life building & perks",
    contents: [
      "- 8-20% cashback on 80 retailers",
      "- Restaurants and entertainment perks",
      "- Members parties & socials",
      "- Free coffee,beer & prosecco",
      "- Grow & view your credit rating",
      "- Work towards a mortgage"
    ],
    footer_1: "£5 per month. Subscription bases",
    footer_2: "Save on av £130 pm"
  },
  {
    img_name: "home.png",
    caption: "Home Pack",
    subcaption_1: "The dream serviced home,",
    subcaption_2: "it's like staying in a hotel",
    contents: [
      "- 24 hour home concierge",
      "- All utilites & energy",
      "- Wifi & Netflix",
      "- All maintenance covered",
      "- All damage covered",
      "- Monthly & End Cleaning"
    ],
    footer_1: "£5 per month subscription",
    footer_2: "Save on av £75 pm"
  },
  {
    img_name: "pets.png",
    caption: "Pets Pack",
    subcaption_1: "Perfect for renters who want to",
    subcaption_2: "live with their pet hassle free.",
    contents: [
      "- Pets Concierge",
      "- Pet passport to rent with them",
      "- Pet damage covered",
      "- Exclusive pets discounts",
      "- Free Goodle Boxes & treats",
      "- Monthly Cleaning"
    ],
    footer_1: "£30 per month subscription",
    footer_2: " Save on average £130 pm"
  },
  {
    img_name: "pets.png",
    caption: "Gold Renter Pack",
    subcaption_1: "Perfect for renters who want to",
    subcaption_2: "live with their pet hassle free.",
    contents: [
      "- Pets Concierge",
      "- Pet passport to rent with them",
      "- Pet damage covered",
      "- Exclusive pets discounts",
      "- Free Goodle Boxes & treats",
      "- Monthly Cleaning"
    ],
    footer_1: "£30 per month subscription",
    footer_2: " Save on average £130 pm"
  },
  {
    img_name: "pets.png",
    caption: "Silver Renter Pack",
    subcaption_1: "Perfect for renters who want to",
    subcaption_2: "live with their pet hassle free.",
    contents: [
      "- Pets Concierge",
      "- Pet passport to rent with them",
      "- Pet damage covered",
      "- Exclusive pets discounts",
      "- Free Goodle Boxes & treats",
      "- Monthly Cleaning"
    ],
    footer_1: "£30 per month subscription",
    footer_2: " Save on average £130 pm"
  }
];
